export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_COLOR_SUCCESS = "ADD_COLOR_SUCCESS";
export const GET_ALL_COLORS = "GET_ALL_COLORS";
export const GET_ALL_COLORS_SUCCESS = "GET_ALL_COLORS_SUCCESS";

export const DELETE_COLOR = "DELETE_COLOR";
export const DELETE_COLOR_SUCCESS = "DELETE_COLOR_SUCCESS";

export const UPDATE_COLOR = "UPDATE_COLOR";
export const UPDATE_COLOR_SUCCESS = "UPDATE_COLOR_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_ALL_MAGASIN = "GET_ALL_MAGASIN";
export const GET_ALL_MAGASIN_SUCCESS = "GET_ALL_MAGASIN_SUCCESS"
export const ADD_MAGASIN = "ADD_MAGASIN";


export const ADD_TENDANCE = "ADD_TENDANCE";
export const ADD_TENDANCE_SUCCESS = "ADD_TENDANCE_SUCCESS";
export const GET_TENDANCE = "GET_PRODUCTS";
export const GET_TENDANCE_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_DEVIS = "GET_DEVIS";
export const GET_DEVIS_SUCCESS = "GET_DEVIS_SUCCESS";


